/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.2.2/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    `java-library`
    `maven-publish`
}

group = "io.github.vincenzopalazzo"
version = "0.0.2"

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    //implementation("io.github.vincenzopalazzo:material-ui-swing:1.1.1-rc2")
    implementation(files("$projectDir/devlib/LinkLabelUI.jar"))
    implementation(files("$projectDir/devlib/material-ui-swing-1.1.1-rc3.jar"))
}